name: ClassicLaunch
options:
  createIntermediateGroups: true
  deploymentTarget:
    macOS: "13.0"
settings:
  base:
    SWIFT_VERSION: 5.9
configs:
  Debug: debug
  Release: release
targets:
  ClassicLaunchCore:
    type: framework
    platform: macOS
    sources:
      - path: Sources/ClassicLaunchCore
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: ai.openclaw.classiclaunch.core
        PRODUCT_NAME: ClassicLaunchCore
        SKIP_INSTALL: YES

  ClassicLaunch:
    type: application
    platform: macOS
    sources:
      - path: Sources/ClassicLaunchApp
    dependencies:
      - target: ClassicLaunchCore
    info:
      path: Config/ClassicLaunch-Info.plist
      properties:
        CFBundleDisplayName: ClassicLaunch
        CFBundleExecutable: $(EXECUTABLE_NAME)
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleName: $(PRODUCT_NAME)
        CFBundlePackageType: APPL
        CFBundleShortVersionString: 0.1.0
        CFBundleVersion: 1
        LSMinimumSystemVersion: "13.0"
        LSApplicationCategoryType: public.app-category.productivity
        NSPrincipalClass: NSApplication
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: ai.openclaw.classiclaunch
        PRODUCT_NAME: ClassicLaunch
        CODE_SIGN_ENTITLEMENTS: Config/ClassicLaunch.entitlements
        ENABLE_HARDENED_RUNTIME: YES
        GENERATE_INFOPLIST_FILE: NO

  ClassicLaunchCoreTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: Tests/ClassicLaunchCoreTests
    dependencies:
      - target: ClassicLaunchCore
    settings:
      base:
        BUNDLE_LOADER: ""
        GENERATE_INFOPLIST_FILE: YES

schemes:
  ClassicLaunch:
    build:
      targets:
        ClassicLaunch: all
        ClassicLaunchCore: [run, test, profile, analyze]
    run:
      config: Debug
    test:
      config: Debug
      gatherCoverageData: true
      targets:
        - ClassicLaunchCoreTests
    archive:
      config: Release
